<?php
header('Cache-Control: no-cache, must-revalidate');
//header('Expires: Mon, 26 Jul 1997 05:00:00 GMT');
header('Content-type: application/json; charset=utf-8');

?>
{
	"sampleRoot":"http://<?=$_SERVER['SERVER_NAME']?>/audio/samples/",
	"samples":[
		{
			"src":"African_Mist_Voice_1.ogg",
			"title":"African Mist Voice 1",
			"family":"vocal",
			"country":"South Africa",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"African_Mist_Voice_2.ogg",
			"title":"African Mist Voice 2",
			"family":"vocal",
			"country":"South Africa",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Backroads_Banjo.ogg",
			"title":"Backroads Banjo",
			"family":"guitar",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Cuban_Percussion.ogg",
			"title":"Cuban Percussion",
			"family":"drum",
			"country":"Cuba",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Djembe.ogg",
			"title":"Djembe",
			"family":"drum",
			"country":"Mali",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Electro_Transistor_Beat.ogg",
			"title":"Electro Transistor Beat",
			"family":"drum",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Hip_Hop_Wakka_Guitar.ogg",
			"title":"Hip Hop Wakka Guitar",
			"family":"guitar",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"House_Lazy_Beat.ogg",
			"title":"House Lazy Beat",
			"family":"drum",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Jazz_Piano.ogg",
			"title":"Jazz Piano",
			"family":"strings",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Cuban_Voice.ogg",
			"title":"Cuban Voice",
			"family":"vocal",
			"country":"Cuba",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Eastern_Gold_Voice.ogg",
			"title":"Eastern Gold Voice",
			"family":"vocal",
			"country":"Egypt",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Koto.ogg",
			"title":"Koto",
			"family":"guitar",
			"country":"Japan",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Sine_Bass.ogg",
			"title":"Sine Bass",
			"family":"guitar",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"Tremolo_Organ.ogg",
			"title":"Tremolo Organ",
			"family":"strings",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		},
		{
			"src":"xxxfilenamexxx.ogg",
			"title":"XXXTITLEXXX",
			"family":"strings",
			"country":"U.S.A.",
			"artist":"",
			"artistId":"",
			"tempo":"120",
			"duration":"4000",
			"key":"*",
			"selected":"1"
		}
	]
}
